-- DDL generated by Postico 2.0 RC 5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE payment (
    id SERIAL PRIMARY KEY,
    payment_id uuid,
    sender text,
    receiver text,
    dao uuid,
    amount text,
    currency text,
    task_id uuid,
    transaction_hash text,
    initiated_at text,
    completed_at text,
    created_at time without time zone,
    updated_at time without time zone,
    payment_type text,
    created_by uuid,
    status text,
    chain_id integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX payment_pkey ON payment(id int4_ops);
